name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dylan-lang/install-opendylan@v2

      - name: Build template-test
        run: ./dylan-compiler -build template-test

      - name: Run template-test
        run: _build/bin/template-test test/sample-template.txt
